MCwrapper/Gcontrol.in, MCwrapper/gluex_MC.py, MCwrapper/gluex_MC.py~, MCwrapper/script.sh
new home for MCwrapper.  Also default swif submits to centOS7
=> initial commit to new location

MCwrapper/Generators/gen_2pi_amp/examples/gen_2pi_amp.cfg, MCwrapper/MakeMC.csh
this paves the way for inclusion of all amptools style generators.
=> added support for gen_2pi_amp

MCwrapper/Gcontrol.in, MCwrapper/MakeMC.csh, MCwrapper/MakeMC.sh, MCwrapper/gluex_MC.py
ver 1.1 with bash support and minor fixes
=> Bash version

MCwrapper/MakeMC.csh, MCwrapper/MakeMC.sh, MCwrapper/examples/MC.config, MCwrapper/gluex_MC.py
merge with small bug fixes and new feature to run custom plugins
=> Custom plugins

MCwrapper/MakeMC.csh, MCwrapper/MakeMC.sh, MCwrapper/gluex_MC.py
pulling in some changes before developing for multiple batch systems
=> now can call swif=2 which will run the workflow after submitting

TOF_calib/DO_CALIB.csh, TOF_calib/README, TOF_calib/domeantime.csh, TOF_calib/dotimediff.csh, TOF_calib/src/consolidate.C, TOF_calib/src/doadctimeoffsets.C, TOF_calib/src/dofitall.C, TOF_calib/src/meantime1.C, TOF_calib/src/timedifference.C, TOF_calib/src/walk1.C
=> modified tof calbiration with walk correction based on amplitude

disk_management/disk_database.pl
make a scratch copy of the tables first.
=> Scratch copy first

MCwrapper/MakeMC.csh, MCwrapper/MakeMC.sh
=> change wasn't properly committed

TOF_calib/DO_CALIB.csh, TOF_calib/src/doadctimeoffsets.C, TOF_calib/src/dofitall.C, TOF_calib/src/meantime1.C, TOF_calib/src/meantime2.C, TOF_calib/src/tdlook.C, TOF_calib/src/timedifference.C, TOF_calib/src/walk1.C, TOF_calib/src/walkAMP1.C
minor modifications to the calibration trying to improve on fit stability and results
=> Tofcalupdate

AnalysisHowTo/ChiSqComparison/DSelector_kpkm.C, AnalysisHowTo/ChiSqComparison/DSelector_kpkm.h, AnalysisHowTo/ChiSqComparison/README.md, AnalysisHowTo/ChiSqComparison/config_test_sig.cfg
* Created directory for ChiSq comparison tutorial
* Created an example DSelector
* Created a configuration file for ROOT's TEnv
* Created a README detailing the analysis workflow
=> ChiSq Comparison Tutorial

split_sim-recon/Makefile
against its full (old) sim-recon parent.
=> Create local version file so that new gluex_sim repo can be build

ANALaunch/MakeANALaunch.py, ANALaunch/web/SubmitReaction.html, ANALaunch/web/utilities/LineWriter.php
initial add/commit on ANA launch project
=> Ana launch

b1pi_test/b1pi_test.sh
Echo the commands to stdout before executing them.
=> Set JANA_CALIB_CONTEXT to use mc variation.

PWA_scripts/bin_data/divideData.py, PWA_scripts/bin_data/gen_amp.conf, PWA_scripts/bin_data/gen_template.cfg
also gives a reasonable starting value for the amplitude
projects:
- add parser for command line options
- switch between mass and t binning
- run fit program
=> python script to bin amptools trees in t bins

psflux/README.md
One flag was mislabled for the flux python script
=> Fix README docs

FlattenForFSRoot/flatten.cc
=> FlattenForFSRoot:  added a "safe mode" for bounds checking

b1pi_test/b1pi_test.sh, b1pi_test/my_b1pi_test.sh
Allow b1pi test to use either hdgeant or hdgeant4 depending on the presence of the -4 option.
=> Choose to run hdgeant4 with -4 option

disk_management/volatile_html.py
directories with files at risk).
=> List directories until old file size sum = used - reserved (i.e.,

TOF_calib/DO_CALIB.csh, TOF_calib/domeantime.csh, TOF_calib/src/consolidate.C, TOF_calib/src/doadctimeoffsets.C, TOF_calib/src/dofitall.C, TOF_calib/src/meantime1.C, TOF_calib/src/meantime2.C, TOF_calib/src/tdlook.C, TOF_calib/src/timedifference.C, TOF_calib/src/walk1.C
after some debugging and changes I hope this will take care of most problems and make the calibration compatible with the new TOF 2 geometry. It was tested with old data so it is backwards compatible.
=> fix some bugs to make calibration compatible with new TOF 2 geometry

TOF_calib/src/dofitall.C, TOF_calib/src/tdlook.C, TOF_calib/src/walk1.C
fix more bugs in the determination of the single ended paddles offset parameters to be compliant with
the new TOF geometry
=> Tofcalmorebugfixes

b1pi_test/b1pi_cron_one.sh, b1pi_test/b1pi_test.sh
=> B1pi test repairs

run_tracking_form/checklist_run.tex
=> Add printing instructions.

CovarianceMatrix/bcal_photon_covariance/JEventProcessor_bcal_photon_covariance.cc, CovarianceMatrix/bcal_photon_covariance/JEventProcessor_bcal_photon_covariance.h, CovarianceMatrix/bcal_photon_covariance/SConstruct, CovarianceMatrix/fcal_photon_covariance/JEventProcessor_fcal_photon_covariance.cc, CovarianceMatrix/fcal_photon_covariance/JEventProcessor_fcal_photon_covariance.h, CovarianceMatrix/fcal_photon_covariance/SConstruct
This is the code that was used to determine the covariance matrices for the BCAL and FCAL in 2016.
Committed for posterity.  It has not been checked that it compiles or runs with the modern halld_sim and halld_recon.  This year we expect to update the covariance matrices but this will likely require numerous changes to this code.
=> Covariance matrices

FlattenForFSRoot/Makefile, FlattenForFSRoot/flatten.cc
Changed the tree name from ntFSGlueX to ntFSGlueX_[code2]_[code1].
=> flattenForFSRoot tree name

AnalysisHowTo/PIDstudy/README, AnalysisHowTo/PIDstudy/input_file_labels.txt, AnalysisHowTo/PIDstudy/plotPIDdataMC.py
Read list of files for comparison from input and add command line arguments for 1D plots of momentum slices.
=> PID systematic study plotting improvement

TOF_calib/DO_CALIB.csh, TOF_calib/findped.py, TOF_calib/ped2db.py, TOF_calib/src/baseline.C, TOF_calib/src/calview.C, TOF_calib/src/consolidate.C, TOF_calib/src/doadctimeoffsets.C, TOF_calib/src/dofitall.C, TOF_calib/src/drawp.C, TOF_calib/src/findp.C, TOF_calib/src/fiteloss.C, TOF_calib/src/meantime1.C, TOF_calib/src/meantime2.C, TOF_calib/src/timedifference.C, TOF_calib/src/viewwalk.C, TOF_calib/src/vtest.C, TOF_calib/src/walk1.C, TOF_calib/todb.py, TOF_calib/viewwalk.C, TOFmon/JEventProcessor_TOFmon.cc, TOFmon/JEventProcessor_TOFmon.h, TOFmon/SConstruct, TOFmon/doall.py, TOFmon/escal.py, TOFmon/findamp.C, TOFmon/sumup.py, TOFmon/usejsub.py
try to make sure no code for the tof calibration gets lost and is available to anyone interesed.
=> save TOF calibration work for future calibrations

FlattenForFSRoot/flatten.cc
Also flatten trees with only generator-level information (same format as before).
=> Flatten generator-level analysis trees.

EfficiencyUtilities/NeutralUtilities/DSelectors/CostheEff/DSelector_pi0pippim__B4_ver21.C, EfficiencyUtilities/NeutralUtilities/DSelectors/CostheEff/DSelector_pi0pippim__B4_ver21.h, EfficiencyUtilities/NeutralUtilities/DSelectors/CostheEff/README, EfficiencyUtilities/NeutralUtilities/DSelectors/CostheEff/call_DSelector.C, EfficiencyUtilities/NeutralUtilities/DSelectors/CostheEff/jana.config, EfficiencyUtilities/NeutralUtilities/DSelectors/CostheEff/plot_compare2DEff.C, EfficiencyUtilities/NeutralUtilities/DSelectors/CostheEff/plot_pi0pippim.C, EfficiencyUtilities/NeutralUtilities/DSelectors/CostheEff/streamline.csh, EfficiencyUtilities/NeutralUtilities/DSelectors/CostheEff/streamline_gen.csh
Added a folder to place the scripts that are used to process data using the CostheEff method. A README file is also included. with instructions on how to run. None of these affect normal GlueX processing.
=> Elton costhe eff

b1pi_test/b1pi_test.sh
Hopefully this will fix the b1pi_test.
=> Add BEAM card to control.in for b1pi_test.

Vertex_scripts/README.md, Vertex_scripts/z_res_mc.C
Made directory Vertex_scripts, added one script and a README.
=> script to find vertex z resolution from MC analysis tree file

profiling/profile_hd_root.sh
add a profiling test of hd_root
=> Profiling2

cppFMWPC/JEventProcessor_cppFMWPC.cc, cppFMWPC/JEventProcessor_cppFMWPC.h, cppFMWPC/SConstruct
this is a plugin to look at raw data from FMWPC. the muon wire chambers for the CPP/NPP experiment
=> add plugin to start working with FMWPC for the cpp experiment

disk_management/disk_database.pl
=> add mtime to the database

disk_management/disk_database.pl
=> Remove debug-only maxdepth specification.

disk_management/.gitignore, disk_management/disk_report.pl
Create a list of user reports that are needed.
=> Re-order sections of report.

disk_management/create_disk_report.sh, disk_management/disk_report.pl
Bring top-level script into line with changes to disk_report.pl.
=> Fix report making

PythonTools/gluupy/EXAMPLE_histmaker_eta_3pi0.py, PythonTools/gluupy/README.md, PythonTools/gluupy/gluupy_histmaker.py
gluupy uses uproot+numpy+PyROOT to efficiently read ROOT trees, perform cuts, accidental weighting, prevent double counting, and create histograms with emphasis on making user code as lightweight as possible.
With some initial tests, we can easily process over 1.5 million combos / sec with good scaling (up to ~10 GB inputs tested). I hope that this can be a jumping off point for more python-based solutions in the future.
I created the directory PythonTools to house this, in case anyone coming along with other python-based stuff wants to use the same directory and avoid more bloat in the top directory.
=> gluupy: a python-based i/o and histogram tool for GlueX

PythonTools/gluupy/EXAMPLE_histmaker_eta_3pi0.py, PythonTools/gluupy/gluupy_histmaker.py
Also shorten example code a tiny bit, reduce the number of cuts applied.
=> Change required branch names to match DSelector flat tree format

kinfitter/monitoring/GraphRunPeriod_pippimpi0_ver1.py, kinfitter/monitoring/GraphRunPeriod_pippimpi0_ver2.py, kinfitter/monitoring/README.md
(code from summer project with University of Regina student Madison Blatchford)
=> Add kinfitter monitoring/plotting code

README.md, get_file_time/README.md, get_file_time/get_file_time.py
python script to estimate the start time of any evio file using DCODAROCInfo objects in that file and the 000 file (if available)
=> Nsj evio file time

launch_scripts/launch/copy_osg.py, launch_scripts/launch/jana_analysis_osg.config, launch_scripts/launch/jobs_analysis_osg.config, launch_scripts/launch/launch_osg.py, launch_scripts/launch/osg-container.sh, launch_scripts/launch/osg_env.sh, launch_scripts/launch/script_osg.sh
This is a start, lightly tested
More tests in progress - also need to add some database driven stuff
=> Scripts for analysis launches on the OSG

psflux/plot_flux_ccdb.py
Correct an off-by-one counting error in the luminosity calculation for the highest energy bin
=> Fix calculation of luminosity for highest energy bin

CDC_scripts/README.md, CDC_scripts/calc_ttod/calc_ttod_from_epics.C
Added a script to estimate CDC time to distance calibration params
=> Nsj ttod script

TOF_calib/src/consolidate.C
ended paddles. instread of averaging over both planes handle the two planes separately.
=> fix minor bug that calculated the average speed of ligth for the single

psflux/plot_flux_ccdb.py
Line modified for RCDB connection to be compatible with the new AlmaLinux9 environment on the farm
=> Modified RCDB connection for the new AlmaLinux9 environment

rootlocks/JEventProcessor_buggy_example.cc, rootlocks/README.md, rootlocks/checklocks.py
and a buggy example to test it on
=> python script to check plugin code for root locks

FlattenForFSRoot/flatten.cc
Fixed a memory bug that showed up as corrupted thrown information in rare cases.  Also added more debugging options (-print 2).
=> memory bug fix
